error_log /logs/error.log;
pid /logs/catsurf.pid;

server 
{
    listen 127.0.0.1:8080;
    server_name catsurf.com www.catsurf.com cat-surf.com;
    root www;
    index index.html;
    error_page 404 /error_pages/404.html;
    
    location /about {
        root www/about;
    }
}

server
{
    listen 127.0.0.1:8080;
    server_name myaccount.catsurf.com;
    root www/account;
    index profile.html;
    
    location /personal {

    }
    location /security {

    }
}

server
{
    listen 127.0.0.1:8080;
    server_name blog.catsurf.com;
    root www/blog;
    index index.html;
    
    location /posts {
        upload_path uploads;
        index post.html;
    }
}

server
{
    listen 127.0.0.1:8080;
    server_name admin.catsurf.com;
    root www/admin;
    index dashboard.html;
    
    location /users {
        allow_methods GET POST DELETE;
    }
}

